# Generated by Django 5.1.1 on 2025-05-19 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talhao', '0003_alter_talhao_data_plantio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomdacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
                ('descricao', models.TextField(max_length=255)),
                ('geracao', models.DateField(auto_now_add=True)),
                ('talhao_recomendacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Recomendacoes', to='talhao.talhao')),
            ],
        ),
    ]
