# Generated by Django 5.1.1 on 2025-05-23 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fazenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cultura_atual', models.CharField(choices=[('Soja', 'Soja'), ('Milho', 'Milho'), ('Feijão', 'Feijão'), ('Arroz', 'Arroz'), ('Trigo', 'Trigo'), ('Cevada', 'Cevada'), ('Algodão', 'Algodão'), ('Girassol', 'Girassol'), ('Café', 'Café'), ('Cana-de-açúcar', 'Cana-de-açúcar'), ('Laranja', 'Laranja'), ('Limão', 'Limão'), ('Uva', 'Uva'), ('Abacate', 'Abacate'), ('Açaí', 'Açaí'), ('Coco', 'Coco'), ('Tomate', 'Tomate'), ('Alface', 'Alface'), ('Cenoura', 'Cenoura'), ('Cebola', 'Cebola'), ('Batata', 'Batata'), ('Pimentão', 'Pimentão'), ('Agrofloresta', 'Agrofloresta')], max_length=255)),
                ('area', models.CharField(max_length=100)),
                ('data_plantio', models.DateField()),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='talhao', to='fazenda.fazendas')),
            ],
        ),
    ]
