# Generated by Django 5.1.1 on 2025-05-19 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talhao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talhao',
            old_name='Fazenda',
            new_name='fazenda',
        ),
    ]
