# Generated by Django 5.1.1 on 2025-05-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talhao', '0002_rename_fazenda_talhao_fazenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talhao',
            name='data_plantio',
            field=models.DateField(),
        ),
    ]
