# Generated by Django 5.1.1 on 2025-05-19 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talhao', '0003_alter_talhao_data_plantio'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadesAgricola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
                ('produto_utilizado', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField()),
                ('operador', models.CharField(max_length=100)),
                ('observacoes', models.TextField(max_length=255)),
                ('data_execusao', models.DateField()),
                ('talhao_nome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='AtividadesAgricola', to='talhao.talhao')),
            ],
        ),
    ]
