# Generated by Django 5.1.1 on 2025-05-23 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agricultor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fazendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('area_total', models.CharField(max_length=255)),
                ('agricultor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fazendas', to='agricultor.agricultor')),
            ],
        ),
    ]
