# Generated by Django 5.1.1 on 2025-05-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fazenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fazendas',
            name='area_total',
            field=models.FloatField(max_length=255),
        ),
    ]
